name: CI

on:
  pull_request:
  push:

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [ 11 ]
        os: [ macos-latest, ubuntu-latest ]
        setScala3: [ "", "SetScala3"]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}

      - uses: coursier/cache-action@v6

      - name: Run
        run: ./sbt ${{ matrix.setScala3 }} run