name: CI

on:
  pull_request:
  push:

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [ 11 ]
        os: [ macos-latest, ubuntu-latest ]
        # setScala3: [ "", "SetScala3"]
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}

      - name: Setup coursier cache
        uses: coursier/cache-action@v6

      - name: Run
        run: ./sbt run

      - name: Test
        run: ./sbt test